name: Testing PR triggers

on:
  push:
    branches:
      - "develop"
      - "main"
  pull_request_target:
    branches:
      - "develop"
      - "main"

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: GIT checkout
        uses: actions/checkout@v2
    
      - name: Hello
        run: |
          sleep 3
          echo "Hello" ${{ github.actor }}
      
      - name: Test Version
        run: |
          sleep 3
          grep Module_Version *.txt | cut -d \" -f2
          
      - name: Should generate README.md
        uses: ./
        with:
          working-dir: ./
          git-push: true
          git-commit-message: "terraform-docs: automated action"
